### ISSUE TITLE
Can't scrape multiple URLS from overview page

### ISSUE THREAD

**Issue by uditagarwal** [holgerd77/django-dynamic-scraper#51]
Hey! 

I've followed the README from top to bottom, and things work fine. If I get a detail page, the scraper puts it in my database. However, there's a problem with the BASE. 

If there are about 50 entires on an Overview page, it only keeps scraping the first url even though I've made multiple changes to xpath and the xPath returns a list of all such objects if I check in the scrapy shell. I've tried enough, gone through code, but still can't find a possible solution.

**Comment by holgerd77** [comment]
Hey Udit,
that sounds like a problem with your XPaths, the URL (and others as well) are taken relatively to the base element. Have you maybe build your URL XPath with trailing double slashes (something like "//div[@class]/a" or something instead of the relative path ("div[@class]/a")? If you still have problems maybe post the XPaths you used here - if possible together with some HTML extract you want to scrape - then I can have a look at it.

**Comment by uditagarwal** [comment]
Thanks for your help. The fact about relative urls is something I missed in the documentation and using the correct xpaths fixed it right up.
