### ISSUE TITLE
No module named future

### ISSUE THREAD

**Issue by rakanalh** [holgerd77/django-dynamic-scraper#55]
I tried running the latest DDS using Python 2.7.10, the following error appeared:

```
  File "/project/apps/feeds/tasks/__init__.py", line 3, in <module>
    from dynamic_scraper.utils.task_utils import TaskUtils
  File "/usr/local/lib/python2.7/site-packages/dynamic_scraper/utils/task_utils.py", line 2, in <module>
    from future import standard_library
ImportError: No module named future
```

I then figured that i was missing the 'future' package so i installed it. I tried checking what the issue is and it's probably because of this: 83dcf295de6456e3fc505b01ae52d44dd6299079

I am not sure why 'install_requires' has been commented out. This is preventing the package from installing it's dependencies and hence, the error appeared.

**Comment by holgerd77** [comment]
Hi Rakan, I didn't want to include packages like ``Django``, ``Scrapy`` or ``Celery`` in the requirements section since I didn't want people to have their Django version updated automatically when updating the software. I see that commenting out all requirements was a bit over the top. I will re-include the unproblematic requirements like ``pillow`` or ``future`` in the next release.
